### ISSUE TITLE
warc.py read data in 'rb' mode, occurring Unicode Error

### ISSUE THREAD

**Issue by RominYue** [cdegroc/warc-clueweb#1]
When I want to decode/encode the content that read from warc.gz file, there sometimes encounters “ ”'ascii' could not decode xxxx“ or "utf8 could not decode xxxxx"

Seen from source file ,we read the warc.gz file in a 'rb' mode, so how to deal with decode/encode problem?

**Comment by cdegroc** [comment]
Hi @RominYue,

I haven't used this code for a while, but here are two suggestions:
- WARCFile/WARCReader output raw strings that you will need to decode. The errors you receive could simply be due to an invalid WARC file.
- Using 'rb' mode shouldn't hurt on linux/unix. But in any case, you can always override the mode from WARCFile constructor.

Hope this helps.
Clement

**Comment by RominYue** [comment]
Thanks, there is still some error in warc.py, but I have fixed it.
